name: pdmp
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter
  - jupyterlab
  - jupyterlab_vim
  - matplotlib
  - numpy
  - scipy
  - seaborn
  - pyvbmc
  - sympy
  - pip
  - pip:
    - nbdime
    - nbmerge
