name: pdmp
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - jupyter
  - jupyterlab
  - jupyterlab_vim
  - matplotlib
  - numpy>=2.0
  - scipy
  - seaborn
  - sympy
  - pip
  - tqdm
  - pytest
  - pytest-cov
  - snakeviz
  - pytorch
  - gpytorch
  - arviz
