name: pdmp
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - matplotlib
  - numpy>=2.0
  - scipy
  - seaborn
  - pip
  - tqdm
  - pytest
  - pytest-cov
  - snakeviz
  - pytorch
  - gpytorch
  - arviz
  - yapf
  - pyyaml
  - typing-extensions
  - pip:
    - geomloss
